/// Flutter icons Movizz
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Movizz
///      fonts:
///       - asset: fonts/Movizz.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Movizz {
  Movizz._();

  static const _kFontFam = 'Movizz';

  static const IconData trends = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData cross = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe806, fontFamily: _kFontFam);
}
